/**
 * @company 杭州智顺文化传播有限公司
 * @copyright Copyright (c) 2018 - 2018
 */
package com.zhishun.zaotoutiao.dal.mapper;

import com.zhishun.zaotoutiao.core.model.entity.Channels;

import java.util.List;
import java.util.Map;

public interface ChannelsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channels
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     *
     */
    int insert(Channels record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channels
     *
     * @mbggenerated
     */
    int insertSelective(Channels record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channels
     *
     * @mbggenerated
     */
    Channels selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channels
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Channels record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channels
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Channels record);

    /**
     * 根据条件查询导航信息
     * @return
     */
    List<Channels> listChannelsPage(Map<String,Object> map);

    List<Channels> getChannelsList(Map<String,Object>map);
    /**
     * 根据条件获取导航总记录数
     * @param map
     * @return
     */
    int countChannels(Map<String,Object> map);

    /**
     * 导航列表
     * @return
     */
    List<Channels> listChannels();

    /**
     * 获取排序较小的导航
     * @return
     */
    Channels getSmallerOrder(int oldOrderNum);

    /**
     * 获取排序较大的导航
     * @param oldOrderNum
     * @return
     */
    Channels getBiggerOrder(int oldOrderNum);

    /**
     * 获取排序最大的导航
     * @return
     */
    Channels getMaxOrder();

    List<Channels> getTabList(Map map);
}