/**
 * @company 杭州智顺文化传播有限公司
 * @copyright Copyright (c) 2018 - 2018
 */
package com.zhishun.zaotoutiao.dal.mapper;

import com.zhishun.zaotoutiao.core.model.entity.ExchangeRate;

public interface ExchangeRateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_rate
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_rate
     *
     * @mbggenerated
     */
    int insert(ExchangeRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_rate
     *
     * @mbggenerated
     */
    int insertSelective(ExchangeRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_rate
     *
     * @mbggenerated
     */
    ExchangeRate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_rate
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ExchangeRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_rate
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ExchangeRate record);

    /**
     * 获取金币汇率
     * @return
     */
    ExchangeRate getExchangeRate();
}