/**
 * @company 杭州智顺文化传播有限公司
 * @copyright Copyright (c) 2018 - 2018
 */
package com.zhishun.zaotoutiao.dal.mapper;

import com.zhishun.zaotoutiao.core.model.entity.StaticRedEnvelope;

import java.util.List;

public interface StaticRedEnvelopeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_red_envelope
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_red_envelope
     *
     * @mbggenerated
     */
    int insert(StaticRedEnvelope record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_red_envelope
     *
     * @mbggenerated
     */
    int insertSelective(StaticRedEnvelope record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_red_envelope
     *
     * @mbggenerated
     */
    StaticRedEnvelope selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_red_envelope
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StaticRedEnvelope record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_red_envelope
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StaticRedEnvelope record);

    /**
     * 兑换微信红包
     * @return
     */
    List<StaticRedEnvelope> listRedEnvelope();
}