/**
 * @company 杭州智顺文化传播有限公司
 * @copyright Copyright (c) 2018 - 2018
 */
package com.zhishun.zaotoutiao.dal.mapper;

import com.zhishun.zaotoutiao.core.model.entity.StaticFakeData;

public interface StaticFakeDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_fake_data
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_fake_data
     *
     * @mbggenerated
     */
    int insert(StaticFakeData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_fake_data
     *
     * @mbggenerated
     */
    int insertSelective(StaticFakeData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_fake_data
     *
     * @mbggenerated
     */
    StaticFakeData selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_fake_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StaticFakeData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_fake_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StaticFakeData record);
}