/**
 * @company 杭州智顺文化传播有限公司
 * @copyright Copyright (c) 2018 - 2018
 */
package com.zhishun.zaotoutiao.dal.mapper;

import com.zhishun.zaotoutiao.core.model.entity.StaticJobs;

import java.util.List;

public interface StaticJobsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_jobs
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_jobs
     *
     * @mbggenerated
     */
    int insert(StaticJobs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_jobs
     *
     * @mbggenerated
     */
    int insertSelective(StaticJobs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_jobs
     *
     * @mbggenerated
     */
    StaticJobs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_jobs
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StaticJobs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_jobs
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StaticJobs record);

    /**
     * 获取岗位列表
     * @param industrysId
     * @return
     */
    List<StaticJobs> listStaticJobs(Long industrysId);
}