/**
 * @company 杭州智顺文化传播有限公司
 * @copyright Copyright (c) 2018 - 2018
 */
package com.zhishun.zaotoutiao.dal.mapper;

import com.zhishun.zaotoutiao.core.model.entity.UserGoldRecord;

public interface UserGoldRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_gold_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_gold_record
     *
     * @mbggenerated
     */
    int insert(UserGoldRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_gold_record
     *
     * @mbggenerated
     */
    int insertSelective(UserGoldRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_gold_record
     *
     * @mbggenerated
     */
    UserGoldRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_gold_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserGoldRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_gold_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserGoldRecord record);
}