/**
 * @company 杭州智顺文化传播有限公司
 * @copyright Copyright (c) 2018 - 2018
 */
package com.zhishun.zaotoutiao.dal.mapper;

import com.zhishun.zaotoutiao.core.model.entity.UserSignIn;

import java.util.List;
import java.util.Map;

public interface UserSignInMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sign_in
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sign_in
     *
     * @mbggenerated
     */
    int insert(UserSignIn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sign_in
     *
     * @mbggenerated
     */
    int insertSelective(UserSignIn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sign_in
     *
     * @mbggenerated
     */
    UserSignIn selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sign_in
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserSignIn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sign_in
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserSignIn record);

    /**
     * 判断今天是否已经签到
     * @param map
     * @return
     */
    int isContinuousSingInToday(Map<String,Object> map);

    /**
     * 判断昨天是否已经签到
     * @param userId
     * @return
     */
    List<UserSignIn> isContinuousSignInYesterday(Long userId);

    /**
     * 获取用户已经连续签到的天数
     * @param userId
     * @return
     */
    UserSignIn getUserSignRecord(Long userId);

    /**
     * 获取用户签到数据
     * @param map
     * @return
     */
    List<UserSignIn> getUserSignList(Map<String,Object> map);
}