/**
 * @company 杭州智顺文化传播有限公司
 * @copyright Copyright (c) 2018 - 2018
 */
package com.zhishun.zaotoutiao.dal.mapper;

import com.zhishun.zaotoutiao.core.model.entity.UserChannels;

import java.util.Map;

public interface UserChannelsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_channels
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_channels
     *
     * @mbggenerated
     */
    int insert(UserChannels record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_channels
     *
     * @mbggenerated
     */
    int insertSelective(UserChannels record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_channels
     *
     * @mbggenerated
     */
    UserChannels selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_channels
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserChannels record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_channels
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserChannels record);

    /**
     * 获取我的频道信息
     * @param id
     * @return
     */
    UserChannels getUserChannels(Long id);

    /**
     * 更新我的频道信息
     * @param map
     * @return
     */
    int updateUserChannels(Map map);

}