/**
 * @company 杭州智顺文化传播有限公司
 * @copyright Copyright (c) 2018 - 2018
 */
package com.zhishun.zaotoutiao.dal.mapper;

import com.zhishun.zaotoutiao.core.model.entity.UserMoneyRecord;

public interface UserMoneyRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_money_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_money_record
     *
     * @mbggenerated
     */
    int insert(UserMoneyRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_money_record
     *
     * @mbggenerated
     */
    int insertSelective(UserMoneyRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_money_record
     *
     * @mbggenerated
     */
    UserMoneyRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_money_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserMoneyRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_money_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserMoneyRecord record);
}