/**
 * @company 杭州智顺文化传播有限公司
 * @copyright Copyright (c) 2018 - 2018
 */
package com.zhishun.zaotoutiao.dal.mapper;

import com.zhishun.zaotoutiao.core.model.entity.UserJpush;

import java.util.Map;

public interface UserJpushMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_jpush
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_jpush
     *
     * @mbggenerated
     */
    int insert(UserJpush record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_jpush
     *
     * @mbggenerated
     */
    int insertSelective(UserJpush record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_jpush
     *
     * @mbggenerated
     */
    UserJpush selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_jpush
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserJpush record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_jpush
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserJpush record);

    /**
     * 获取用户推送信息
     * @param map
     * @return
     */
    UserJpush getUserJpush(Map map);

    /**
     * 判断是否是今天
     * @param time
     * @return
     */
    int isToday(String time);
}