/**
 * @company 杭州智顺文化传播有限公司
 * @copyright Copyright (c) 2018 - 2018
 */
package com.zhishun.zaotoutiao.dal.mapper;

import com.zhishun.zaotoutiao.core.model.entity.UserAttention;

public interface UserAttentionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_attention
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_attention
     *
     * @mbggenerated
     */
    int insert(UserAttention record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_attention
     *
     * @mbggenerated
     */
    int insertSelective(UserAttention record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_attention
     *
     * @mbggenerated
     */
    UserAttention selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_attention
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserAttention record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_attention
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserAttention record);
}