/**
 * @company 杭州智顺文化传播有限公司
 * @copyright Copyright (c) 2018 - 2018
 */
package com.zhishun.zaotoutiao.dal.mapper;

import com.zhishun.zaotoutiao.core.model.entity.Channels;
import com.zhishun.zaotoutiao.core.model.entity.VideoChannels;

import java.util.List;

public interface VideoChannelsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channels
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     *
     */
    int insert(Channels record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channels
     *
     * @mbggenerated
     */
    int insertSelective(Channels record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channels
     *
     * @mbggenerated
     */
    Channels selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channels
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Channels record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channels
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Channels record);

    /**
     * 获取视频分类列表
     * @return
     */
    List<VideoChannels> listVideoChannels();
}