/**
 * @company 杭州智顺文化传播有限公司
 * @copyright Copyright (c) 2018 - 2018
 */
package com.zhishun.zaotoutiao.common.dal.mapper;

import com.zhishun.zaotoutiao.core.model.entity.Channels;

public interface ChannelsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channels
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channels
     *
     * @mbggenerated
     */
    int insert(Channels record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channels
     *
     * @mbggenerated
     */
    int insertSelective(Channels record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channels
     *
     * @mbggenerated
     */
    Channels selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channels
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Channels record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channels
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Channels record);
}