/**
 * @company 杭州智顺文化传播有限公司
 * @copyright Copyright (c) 2018 - 2018
 */
package com.zhishun.zaotoutiao.common.dal.mapper;

import com.zhishun.zaotoutiao.core.model.entity.DispatchChannel;

public interface DispatchChannelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispatch_channel
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispatch_channel
     *
     * @mbggenerated
     */
    int insert(DispatchChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispatch_channel
     *
     * @mbggenerated
     */
    int insertSelective(DispatchChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispatch_channel
     *
     * @mbggenerated
     */
    DispatchChannel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispatch_channel
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DispatchChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispatch_channel
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(DispatchChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispatch_channel
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DispatchChannel record);
}