/**
 * @company 杭州智顺文化传播有限公司
 * @copyright Copyright (c) 2018 - 2018
 */
package com.zhishun.zaotoutiao.dal.mapper;

import com.zhishun.zaotoutiao.core.model.entity.StaticGoldConfig;

public interface StaticGoldConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_gold_config
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_gold_config
     *
     * @mbggenerated
     */
    int insert(StaticGoldConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_gold_config
     *
     * @mbggenerated
     */
    int insertSelective(StaticGoldConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_gold_config
     *
     * @mbggenerated
     */
    StaticGoldConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_gold_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StaticGoldConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_gold_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StaticGoldConfig record);
}